# Generated by Django 5.0.4 on 2024-04-15 06:09

import livros_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=livros_app.models.up_imagem_livro),
        ),
    ]
